### ISSUE TITLE
GPIO not working on CM4/CM4IO

### ISSUE THREAD

**Issue by DraconicMatty** [renetec-io/Pyxian#22]
Fresh install of latest Pyxian 0.6.4. GPIO 21 works fine to get back to settings, but the included GPIO example does not work. It won't show any pin states and toggling GPIO 23 does not bring the pin high.

![Screenshot](https://user-images.githubusercontent.com/42086791/111709974-10135c00-881f-11eb-8b2a-a555421ddbac.png)

**Comment by shtig** [comment]
Thank you for reporting the issue. I will look into that.

**Comment by DraconicMatty** [comment]
Thanks!

**Comment by shtig** [comment]
I found the source of the problem. It is an outdated pigpio daemon that does not support Compute Module 4. Unfortunately, there is no package with a newer version yet, so we cannot easily update it with apt. 
I will be looking into how to update it in the next distribution. In meanwhile, you can install it manually by ssh-ing to the device:
1. Update everything
```
sudo apt-get update
sudo apt-get upgrade
```
2. Install tools:
```
sudo apt-get install python-setuptools python3-setuptools
```
3. Install the latest pigpiod manually:
```
wget https://github.com/joan2937/pigpio/archive/master.zip
unzip master.zip
cd pigpio-master
make
sudo make install
```
4. Check the version, you should get 79 or above.
```
pigpiod -v
```
5. Reboot:
```
sudo reboot
```
GPIO must now work.

**Comment by DraconicMatty** [comment]
Tested and working great, thanks!
